import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {SocketProvider} from "@/providers/SocketProvider";
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Telegram Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html
				className='dark'
				lang='en'
			>
				<body className={inter.className}>
					<SocketProvider>{children}</SocketProvider>
				</body>
			</html>{" "}
		</ClerkProvider>
	);
}
